import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { io, Socket } from 'socket.io-client';
import Chat from '../../components/Quiz/Chat/Chat';
import Sidebar from '../../components/Quiz/Sidebar/Sidebar';
import WaitingRoom from '../../components/Quiz/WaitingRoom/WaitingRoom';
import { GameState } from '../../lib/types';

const Quiz: NextPage = () => {
  const userId = Math.round(Math.random() * 1000);
  const userName = `User${userId}`;
  const router = useRouter();
  const { quiz } = router.query;
  const [socket, setSocket] = useState<Socket>();
  const [gameState, setGameState] = useState<GameState>('waiting');

  useEffect(() => {
    if (process.env.NEXT_PUBLIC_SERVER_URL) {
      setSocket(io(process.env.NEXT_PUBLIC_SERVER_URL));
    } else {
      router.push('/?error=socket-connection', '/');
    }
  }, []);

  useEffect(() => {
    socket?.on('game-started', () => {
      router.push('/?error=game-started', '/');
    });

    socket?.on('game-full', () => {
      router.push('/?error=game-full', '/');
    });

    socket?.on('game-state', (newGameState: GameState) => {
      setGameState(newGameState);
    });

    return () => {
      socket?.close();
    };
  }, [socket]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>A random quiz</h1>
        {socket && quiz
          ? (
            <>
              {gameState === 'waiting'
                ? <WaitingRoom socket={socket} />
                : null}
              <Chat
                socket={socket}
                userName={userName}
                userId={userId}
                room={quiz as string}
              />
              <Sidebar
                socket={socket}
                userName={userName}
                userId={userId}
              />
            </>
          )
          : null}
      </main>
    </>
  );
};

export default Quiz;
