import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { getProviders, getSession, signIn } from 'next-auth/react';
import { AppProviders } from 'next-auth/providers';

type Props = {
  providers: AppProviders
}

const SignIn: NextPage<Props> = ({ providers }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {Object.values(providers).map((provider) => (
          <div key={provider.name}>
            <button type="button" onClick={() => signIn(provider.id)}>
              Sign in with
              {provider.name}
            </button>
          </div>
        ))}
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
      props: {},
    };
  }

  const providers = await getProviders();
  return {
    props: {
      providers,
    },
  };
};

export default SignIn;
