import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { getSession, signIn } from 'next-auth/react';
import Particules from '../components/Common/Particules/Particules';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main>
      <Particules />
      <p>Not signed in.</p>
      <button type="button" onClick={() => signIn()}>Sign in</button>
    </main>
  </>
);

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });
  if (session) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export default Home;
