import { useReducer, useState } from 'react';
import { GetServerSideProps, NextPage } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ObjectId } from 'mongodb';
import SettingBar from '../../components/Creator/SettingBar/SettingBar';
import Particules from '../../components/Common/Particules/Particules';
import QuizEditor from '../../components/Creator/QuizEditor/QuizEditor';
import { EditorContext, questionsReducer } from '../../lib/contexts/EditorContext';
import clientPromise from '../../lib/utils/mongodb';
import isNotEmpty from '../../lib/utils/isNotEmpty';
import MenuIcon from '../../public/icons/iconComponents/MenuIcon';
import { QuizData, UserFromDB } from '../../lib/types';
import styles from '../../styles/pages/Creator.module.scss';

type Props = {
  quizId: string,
  quizData?: QuizData,
};

const Creator: NextPage<Props> = ({ quizId, quizData }: Props) => {
  const [settings, setSettings] = useState<QuizData | undefined>(quizData);
  const [questions, dispatchQuestions] = useReducer(questionsReducer, quizData?.questions);
  const [settingBarVisible, setSettingBarVisible] = useState(false);
  const router = useRouter();

  const saveQuiz = async (publish: boolean) => {
    const response = await fetch('/api/save-quiz', {
      method: 'POST',
      body: JSON.stringify({
        _id: quizId,
        ...settings,
        questions,
        status: publish ? 'published' : 'draft',
      }),
    });
    if (response.ok) {
      /* TODO: handle quiz is saved */
    } else {
      /* TODO: handle quiz cannot be saved */
    }
  };

  const handleSaveQuiz = () => {
    if (settings?.title !== '') {
      saveQuiz(false);
    } else {
      /* TODO: handle title required */
    }
  };

  const publishQuiz = () => {
    if (settings && questions && questions.length > 3 && isNotEmpty({ ...settings, questions })) {
      saveQuiz(true);
    } else {
      /* TODO: handle quiz cannot be published */
    }
  };

  const deleteQuiz = async () => {
    const response = await fetch('/api/delete-quiz', {
      method: 'POST',
      body: quizId,
    });
    if (response.ok) {
      router.push('/?alert=quiz-succesfully-deleted', '/');
    } else {
      /* TODO: handle quiz cannot be deleted */
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Particules />
      <header className={styles.header}>
        <h1 className={styles.hero}>{settings?.title || 'Your new quiz'}</h1>
        <button className={styles.menu} onClick={() => setSettingBarVisible(true)} type="button">
          <MenuIcon />
        </button>
        <div className={styles.buttonContainer}>
          <button className={`${styles.button} ${styles.green}`} type="button" onClick={handleSaveQuiz}>Save</button>
          <button className={`${styles.button} ${styles.blue}`} type="button" onClick={publishQuiz}>Publish</button>
          <button className={`${styles.button} ${styles.red}`} type="button" onClick={deleteQuiz}>Delete quiz</button>
        </div>
      </header>
      <div className={styles.gradient} />
      <EditorContext.Provider value={{ questions, dispatchQuestions }}>
        <QuizEditor />
      </EditorContext.Provider>
      <SettingBar
        visible={settingBarVisible}
        hide={() => setSettingBarVisible(false)}
        setSettings={setSettings}
        defaultData={quizData}
      />
    </>
  );
};

Creator.defaultProps = {
  quizData: {
    status: 'draft',
    questions: [
      {
        id: 1,
        question: '',
        responses: [
          { id: 1, value: '' },
          { id: 2, value: '' },
        ],
        correct: 0,
      },
    ],
  },
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: '/auth/signin',
      },
      props: {},
    };
  }

  const quiz = context.params?.quiz as string | undefined;
  if (!quiz) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
      props: {},
    };
  }
  if (quiz === 'new') {
    const { _id: userId } = session.user as UserFromDB;
    const client = await clientPromise;
    const response = await client.db().collection('quizzes').insertOne({ userId });
    const quizId = response.insertedId.toHexString();
    client.close();

    return {
      props: {
        quizId,
      },
    };
  }
  const client = await clientPromise;
  const response: { _id: ObjectId | string } | null = await client
    .db()
    .collection('quizzes')
    .findOne({ _id: new ObjectId(quiz) });
  if (response && (response as QuizData).userId === (session.user as UserFromDB)._id) {
    response._id = quiz;

    return {
      props: {
        quizId: quiz,
        quizData: response,
      },
    };
  }

  return {
    redirect: {
      permanent: false,
      destination: '/',
    },
    props: {},
  };
};

export default Creator;
