import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { io, Socket } from 'socket.io-client';
import Chat from '../components/Quiz/Chat/Chat';
import Sidebar from '../components/Quiz/Sidebar/Sidebar';

const Quiz: NextPage = () => {
  const userId = Math.round(Math.random() * 1000);
  const userName = `User${userId}`;
  const room = 'room1';
  const [socket, setSocket] = useState<Socket>();

  useEffect(() => {
    if (process.env.NEXT_PUBLIC_SERVER_URL) {
      setSocket(io(process.env.NEXT_PUBLIC_SERVER_URL));
    } else {
      /* TODO: handle error */
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>A random quiz</h1>
        {socket
          ? (
            <>
              <Chat
                socket={socket}
                userName={userName}
                userId={userId}
                room={room}
              />
              <Sidebar socket={socket} />
            </>
          )
          : null}
      </main>
    </>
  );
};

export default Quiz;
